export const dalmutiCode = [
  "import random",
  "import numpy as np",
  "import pandas as pd",
  "import seaborn as sns",
  "import matplotlib.pyplot as plt",
  "import tqdm",
  "",
  "# 달무티 확률표 계산기",
  "for players in range(6, 8): # 플레이어 수 조정 x~y-1인",
  "    end_card = 13 # 4인 경우 12,11을 제외해야 해서 11로 실행, 5인의 경우 12를 제외하고 12로 실행",
  "    deck = [n for n in range(1, end_card) for _ in range(n)]",
  "    random.shuffle(deck)",
  "    hands = [[] for _ in range(players)]",
  "    # 시뮬레이션 횟수(10만번이 시간 대비 가장 무난함. 근데 100만번은 넘어야 재현율이 좋아짐)",
  "    trials = 100000",
  "    # 계산 형태 생성",
  "    probs = np.zeros((end_card, end_card))",
  "    commits = np.zeros((end_card, end_card))",
  "    successes = np.zeros((end_card, end_card))",
  "    # 시뮬레이션 계산",
  "    for _ in tqdm.tqdm(range(trials)):",
  "        # 카드 섞기",
  "        random.shuffle(deck)",
  "        # 카드 분배",
  "        hands = [[] for _ in range(players)]",
  "        for i, card in enumerate(deck):",
  "            hands[i % players].append(card)",
  "        # 카드 카운트",
  "        counts = np.zeros((players, end_card))",
  "        for i, hand in enumerate(hands):",
  "            for card in hand:",
  "                counts[i, card] += 1",
  "        # 모든 경우의 수에 대해 계산",
  "        for card_num in range (end_card):",
  "            for chunk in range(1, card_num + 1):",
  "                if counts[0, card_num] == chunk:",
  "                    commits[chunk, card_num] += 1",
  "                    if not (counts[1:, 1:card_num] == chunk).any():",
  "                        successes[chunk, card_num] += 1",
  "    # 확률 계산",
  "    probs = successes / commits",
  "    # 판다스 생성",
  "    df = pd.DataFrame(probs)",
  "    # 0번째 제거",
  "    df = df.iloc[1:, 1:]",
  "    # 결측치",
  "    df = df.fillna(0)",
  "    # 백분율 변환",
  "    df = (df * 100).round(2)",
  "    # 시각화",
  "    plt.figure(figsize=(10, 10))",
  "    sns.heatmap(df, annot=True, fmt=\".2f\")",
  "    plt.title(f\"Dalmuti probability table (players: {players})\")",
  "    plt.xlabel(\"card number\")",
  "    plt.ylabel(\"number of cards\")",
  "    # plt.savefig(f\"달무티 {players}인 확률표.png\", dpi=300, bbox_inches='tight') # 저장하려면 샵(#) 제거",
  "    plt.show() # 결과값 시각화 플레이어 수 반복 시 닫아야만 반복함",
  "    # plt.close()",
].join("\n");
